//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diplom
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zakaz
    {
        public int IdZakaz { get; set; }
        public int IdHleb { get; set; }
        public decimal Cena { get; set; }
        public string Kolichestvo { get; set; }
        public int IdPeople { get; set; }
    
        public virtual Hlebi Hlebi { get; set; }
        public virtual People People { get; set; }
    }
}
